version: "3.7"

x-default-service: &linux
  working_dir: /qbs
  environment:
    - BUILD_OPTIONS
  volumes:
    - .:/qbs
    - ~/.ccache:/home/devel/.ccache
  network_mode: bridge
  cap_add:
      - SYS_PTRACE

services:
  bionic:
    << : *linux
    hostname: bionic
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:bionic-5.12.8_1.15.1-0
    build:
      dockerfile: docker/bionic/Dockerfile
      context: .
      args:
        QT_VERSION: 5.12.8
        QTCREATOR_VERSION: 4.11.2

  bionic-android-513:
    << : *linux
    hostname: bionic-android
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:bionic-android-5.13.2-2
    build:
      dockerfile: docker/bionic/test-android.Dockerfile
      context: .
      args:
        QT_VERSION: 5.13.2

  bionic-android-514:
    << : *linux
    hostname: bionic-android
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:bionic-android-5.14.0-2
    build:
      dockerfile: docker/bionic/test-android.Dockerfile
      context: .
      args:
        QT_VERSION: 5.14.0

  windows:
    image: ${DOCKER_USER:-qbsbuild}/qbsdev:windowsservercore-5.12.7_1.15.0-0
    build:
      dockerfile: docker/windowsservercore/Dockerfile
      context: .
      args:
        QT_VERSION: 5.12.7
        QBS_VERSION: 1.15.0
    working_dir: 'C:/qbs'
    environment:
      - BUILD_OPTIONS
      - WITH_DOCS
    volumes:
      - .:C:\qbs
      - ~/.ccache:C:\.ccache
    network_mode: nat
